### ISSUE TITLE
Plain TCP load balancing does not work

### ISSUE THREAD

**Issue by aklinkert** [mrlesmithjr/ansible-nginx-load-balancer#1]
Hey there, 

I'm trying to deploy a load balancer using plain tcp as protocol, but I am unable to generate a sane config.

This is an excerpt of my playbook:
```yaml
- name: Install nginx load balancer
  hosts: k8s-lb
  roles:
    - role: mrlesmithjr.nginx-load-balancer
      tags: [lb, load-balancer]
  vars:
    nginx_load_balancer_configs:
      - name: 'ingress_http'
        frontend_listen_port: 80
        method: 'round_robin'
        protocol: 'tcp'
        upstream:
          - servers: "{{ cluster_nodes_ips }}"
            backend_listen_port: 80
      - name: 'ingress_https'
        frontend_listen_port: 443
        method: 'round_robin'
        protocol: 'tcp'
        upstream:
          - servers: "{{ cluster_nodes_ips }}"
            backend_listen_port: 443
      - name: 'k8s_api'
        frontend_listen_port: 6443
        method: 'round_robin'
        protocol: 'tcp'
        upstream:
          - servers: "{{ cluster_masters_ips }}"
            backend_listen_port: 6443
```

which renders into (replaced all ips by <>):
```
# Ansible managed

pid /run/nginx.pid;
user www-data;
worker_processes 4;
include /etc/nginx/modules-enabled/*.conf;
events {
  worker_connections 1024;
}
http {
}
stream {
  upstream ingress_http {
    server <>:80;
  }
  server {
    listen 80 tcp;
    proxy_pass ingress_http;
  }
  upstream ingress_https {
    server <>:443;
  }
  server {
    listen 443 tcp;
    proxy_pass ingress_https;
  }
  upstream k8s_api {
    server <>:6443;
  }
  server {
    listen 6443 tcp;
    proxy_pass k8s_api;
  }
}
```

when using  `protocol: ''`:
```
# Ansible managed

pid /run/nginx.pid;
user www-data;
worker_processes 4;
include /etc/nginx/modules-enabled/*.conf;
events {
  worker_connections 1024;
}
http {
}
stream {
}
```
